import Link from "next/link";
import { CalendarDays, Sparkles } from "lucide-react";
import { CommandCard, CommandCardHeader, PanelLink } from "./CommandCard";

const plan = [
  { day: "MON", title: "Targeted Interventions", detail: "Focus on fractions & decoding gaps", students: "4 students", color: "bg-rose-400" },
  { day: "TUE", title: "Small Group Sessions", detail: "Foundational skills practice", students: "6 students", color: "bg-amber-400" },
  { day: "WED", title: "AI-Recommended Practice", detail: "Adaptive skill building", students: "10 students", color: "bg-cyan-400" },
  { day: "THU", title: "Progress Check", detail: "Quick mastery checks & adjustments", students: "All students", color: "bg-violet-400" },
  { day: "FRI", title: "Skill Reinforcement", detail: "Spaced practice & fluency", students: "8 students", color: "bg-emerald-400" },
];

export function WeeklyPlanCard() {
  return (
    <CommandCard id="weekly-plan" className="scroll-mt-20">
      <CommandCardHeader
        title="Weekly Plan"
        subtitle="May 19 – May 25"
        action={<Link href="/practice-plans"><PanelLink>Edit plan</PanelLink></Link>}
      />
      <div className="divide-y divide-white/[0.05] px-5">
        {plan.map((item) => (
          <div key={item.day} className="flex items-center gap-3 py-3">
            <div className="relative flex h-9 w-9 shrink-0 items-center justify-center rounded-lg border border-white/[0.08] bg-white/[0.025] text-[9px] font-bold tracking-wider text-slate-400">
              <span className={`absolute left-0 top-2 h-5 w-0.5 rounded-r ${item.color}`} />{item.day}
            </div>
            <div className="min-w-0 flex-1"><p className="truncate text-xs font-medium text-slate-200">{item.title}</p><p className="mt-0.5 truncate text-[10px] text-slate-600">{item.detail}</p></div>
            <span className="whitespace-nowrap rounded-full border border-white/[0.07] bg-white/[0.025] px-2 py-1 text-[9px] text-slate-500">{item.students}</span>
          </div>
        ))}
      </div>
      <div className="border-t border-white/[0.055] px-5 py-3">
        <p className="flex items-center gap-2 text-[10px] text-slate-600"><Sparkles className="h-3.5 w-3.5 text-violet-400" />Plan generated by AI based on student needs and goals.</p>
        <Link href="/practice-plans" className="mt-2 inline-flex items-center gap-1 text-xs font-medium text-blue-400 hover:text-cyan-300"><CalendarDays className="h-3.5 w-3.5" />View full plan →</Link>
      </div>
    </CommandCard>
  );
}
